$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
      loop:true,
      singleItem: true,
      margin:10,
      nav:false,
      responsive:{
          0:{
              items:1
          },
          760:{
            items:1
        },
          1000:{
              items:3
          }
      }
  })
  });